/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElD: typeof import('element-plus/es')['ElD']
  const ElDrawer: typeof import('element-plus/es')['ElDrawer']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
}
