/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseBolck: typeof import('./src/components/baseBolck.vue')['default']
    BaseHighBolck: typeof import('./src/components/baseHighBolck.vue')['default']
    copy: typeof import('./src/components/baseBolck copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElO: typeof import('element-plus/es')['ElO']
    ElOverlay: typeof import('element-plus/es')['ElOverlay']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
